[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cryoHub"
authors = [{name = "yilaili", email = "yilai@umich.edu"}]
dynamic = ["version", "description"]
